### ISSUE TITLE
requesting compatibility with Home Assistant Core => 2022.10 regarding deprecated NumberEntity features

### ISSUE THREAD

**Issue by axx4one** [pyalarmdotcom/alarmdotcom#179]
log: 

2022-11-19 15:14:57.126 WARNING (MainThread) [homeassistant.components.number] Entity None (<class 'custom_components.alarmdotcom.number.ConfigOptionNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom integration author.
2022-11-19 15:15:27.660 WARNING (MainThread) [pyalarmdotcomajax.extensions] Couldn't find field None
2022-11-19 15:15:58.594 WARNING (MainThread) [pyalarmdotcomajax.extensions] Couldn't find field None

"[pyalarmdotcomajax.extensions] Couldn't find field None" is being logged every 30 seconds reflecting the update interval.

https://developers.home-assistant.io/docs/core/entity/number/

**Comment by elahd** [comment]
Fixed in v0.2.16. Thanks!

**Comment by axx4one** [comment]
@elahd : Thanks for swiftly taking care of it. 

After updating the integration it now logs:

2022-11-20 18:33:16.098 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2022-11-20 18:33:16.149 ERROR (MainThread) [homeassistant.components.number] Error adding entities for domain number with platform alarmdotcom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 788, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/alarmdotcom/base_device.py", line 93, in async_added_to_hass
    self.update_device_data()
  File "/config/custom_components/alarmdotcom/number.py", line 86, in update_device_data
    self.native_value = float(current_value)
AttributeError: can't set attribute 'native_value'
2022-11-20 18:33:16.174 ERROR (MainThread) [homeassistant.components.number] Error while setting up alarmdotcom platform for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 788, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/alarmdotcom/base_device.py", line 93, in async_added_to_hass
    self.update_device_data()
  File "/config/custom_components/alarmdotcom/number.py", line 86, in update_device_data
    self.native_value = float(current_value)

2022-11-20 18:34:49.134 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/alarmdotcom/base_device.py", line 108, in _handle_coordinator_update
    self.update_device_data()
  File "/config/custom_components/alarmdotcom/number.py", line 86, in update_device_data
    self.native_value = float(current_value)
AttributeError: can't set attribute 'native_value'
AttributeError: can't set attribute 'native_value'

**Comment by axx4one** [comment]
Found another hint for Home Assistant Core 2023.1 that will most likely force lots of custom integrations to be sort of rewritten.

https://developers.home-assistant.io/blog/2022/06/14/number_entity_refactoring/

In Home Assistant Core 2023.1, overriding async_set_value, max_value, min_value, set_value, step, unit_of_measurement, value, setting _attr_max_value, _attr_min_value, _attr_unit_of_measurement, _attr_step, _attr_value and setting max_value, min_value, unit_of_measurement, step on instances of NumberEntityDescription is no longer supported.

**Comment by elahd** [comment]
Shoot, thanks. I pushed out a hotfix. Can you confirm that that works? I don't own any devices that let me directly test this feature.

**Comment by axx4one** [comment]
Thanks. I can confirm... the error messages are gone.

This one still persists:
2022-11-21 15:36:26.424 WARNING (MainThread) [pyalarmdotcomajax.extensions] Couldn't find field None

seems to be unrelated, but would be nice to know why it's being logged.

Thank you very much anyhow.

**Comment by axx4one** [comment]
added debug logger for "pyalarmdotcomajax":


2022-11-21 16:07:44.933 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2022-11-21 16:08:14.001 DEBUG (MainThread) [custom_components.alarmdotcom.alarmhub] custom_components.alarmdotcom.alarmhub: Requesting update from Alarm.com.
2022-11-21 16:08:14.001 DEBUG (MainThread) [pyalarmdotcomajax] Calling update on Alarm.com
2022-11-21 16:08:14.227 DEBUG (MainThread) [pyalarmdotcomajax] Trouble condition response:
{'data': [], 'included': [], 'meta': {'transformer_version': '1.1'}}
2022-11-21 16:08:14.391 DEBUG (MainThread) [pyalarmdotcomajax.extensions] Response status from Alarm.com: 200
2022-11-21 16:08:14.589 WARNING (MainThread) [pyalarmdotcomajax.extensions] Couldn't find field None
2022-11-21 16:08:14.649 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized video/devices/camera Front Door
