### ISSUE TITLE
Unexpected Keyword Argument 'Brightness'

### ISSUE THREAD

**Issue by Lurick73** [pyalarmdotcom/alarmdotcom#459]
**Describe the bug**
When attempting to change brightness on lights with the integration I get an unexpected keyword argument error.

**To Reproduce**

1. Attempt to change brightness level for a light
2. Observe error shows up on screen
3. Additional websocket error in logs

**Expected behavior**
No errors should appear and brightness should adjust

**Screenshots**

![Image](https://github.com/user-attachments/assets/09cb3f5d-0d97-410a-968b-b28c309e4f16)

**Home Assistant Version:**
Core: 2025.5.2
Supervisor: 2025.05.1
Plugin: 4.0.0.beta-4

**Additional context**
Failed to perform the action light/turn_on. LightController.turn_on() got an unexpected keyword argument 'brightness'

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:250
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:42:33 AM (3 occurrences)
Last logged: 7:44:35 AM

[140262740270496] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 250, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 651, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/alarmdotcom/light.py", line 221, in async_turn_on
    await self.entity_description.control_fn(
        self.controller, self.resource_id, "turn_on", kwargs
    )
  File "/config/custom_components/alarmdotcom/light.py", line 126, in control_fn
    await controller.turn_on(light_id, brightness=brightness)
          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LightController.turn_on() got an unexpected keyword argument 'brightness'

**Comment by Lurick73** [comment]
Might be related to #457

**Comment by elahd** [comment]
This is addressed in v4.0.0-beta.5.

**Comment by Rattleheadie** [comment]
Hi @elahd thanks for all your work on this, really appreciate it. I have just tested Beta5 and after a reboot of HA, the issue is still persisting in my case. 

_`2025-05-20 09:18:20.972 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140493530126976] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 250, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 651, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/alarmdotcom/light.py", line 224, in async_turn_on
    await self.entity_description.control_fn(
        self.controller, self.resource_id, "turn_on", kwargs
    )
  File "/config/custom_components/alarmdotcom/light.py", line 129, in control_fn
    await controller.turn_on(light_id, brightness=brightness)
          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LightController.turn_on() got an unexpected keyword argument 'brightness'`_

**Comment by elahd** [comment]
Thanks. Try again with beta 6.

**Comment by Lurick73** [comment]
Seems to be fixed on my side with beta 6 at least for light control.
Dimming seems to have some weird issue where the light is at 100% but the GUI shows it at 39%, not sure if that's related to this or I should open a new issue.

**Comment by Lurick73** [comment]
Opened #467 to track that separately, will close this one out but feel free to reopen if needed.
